### ISSUE TITLE
PHPUnit 9 on 1.4

### ISSUE THREAD

**Issue by gjuric** [jakzal/phpunit-injector#28]
Would it be possible to release a PHPUnit compatible version in the v1.4.* branch?

This package is blocking us from upgrading to PHPUnit 9 since we are still running on PHP 7.3 and I see that you bumped the dependency of PHPUnit in the 2.0 branch that we can not run at the moment.

**Comment by jakzal** [comment]
[v1.4.2](https://github.com/jakzal/phpunit-injector/releases/tag/v1.4.2) released.
