### ISSUE TITLE
Not compatible with phpunit 9

### ISSUE THREAD

**Issue by gvojtko** [jakzal/phpunit-injector#34]
www-data@9609a44bb026:/var/www/html$ composer require --dev zalas/phpunit-injector
Using version ^1.4 for zalas/phpunit-injector
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - zalas/phpunit-injector v1.4.1 requires phpunit/phpunit ^8.0 -> satisfiable by phpunit/phpunit[8.0.0, 8.0.1, 8.0.2, 8.0.3, 8.0.4, 8.0.5, 8.0.6, 8.1.0, 8.1.1, 8.1.2, 8.1.3, 8.1.4, 8.1.5, 8.1.6, 8.2.0, 8.2.1, 8.2.2, 8.2.3, 8.2.4, 8.2.5, 8.3.0, 8.3.1, 8.3.2, 8.3.3, 8.3.4, 8.3.5, 8.4.0, 8.4.1, 8.4.2, 8.4.3, 8.5.0, 8.5.1, 8.5.10, 8.5.11, 8.5.12, 8.5.2, 8.5.3, 8.5.4, 8.5.5, 8.5.6, 8.5.7, 8.5.8, 8.5.9, 8.5.x-dev] but these conflict with your requirements or minimum-stability.
    - zalas/phpunit-injector v1.4.0 requires phpunit/phpunit ^8.0 -> satisfiable by phpunit/phpunit[8.0.0, 8.0.1, 8.0.2, 8.0.3, 8.0.4, 8.0.5, 8.0.6, 8.1.0, 8.1.1, 8.1.2, 8.1.3, 8.1.4, 8.1.5, 8.1.6, 8.2.0, 8.2.1, 8.2.2, 8.2.3, 8.2.4, 8.2.5, 8.3.0, 8.3.1, 8.3.2, 8.3.3, 8.3.4, 8.3.5, 8.4.0, 8.4.1, 8.4.2, 8.4.3, 8.5.0, 8.5.1, 8.5.10, 8.5.11, 8.5.12, 8.5.2, 8.5.3, 8.5.4, 8.5.5, 8.5.6, 8.5.7, 8.5.8, 8.5.9, 8.5.x-dev] but these conflict with your requirements or minimum-stability.
    - Conclusion: remove phpdocumentor/reflection-common 2.2.0
    - Conclusion: don't install phpdocumentor/reflection-common 2.2.0
    - phpdocumentor/reflection-docblock 4.0.1 requires phpdocumentor/reflection-common ^1.0@dev -> satisfiable by phpdocumentor/reflection-common[1.0, 1.0.1].
    - phpdocumentor/reflection-docblock 4.1.0 requires phpdocumentor/reflection-common ^1.0@dev -> satisfiable by phpdocumentor/reflection-common[1.0, 1.0.1].
    - phpdocumentor/reflection-docblock 4.1.1 requires phpdocumentor/reflection-common ^1.0@dev -> satisfiable by phpdocumentor/reflection-common[1.0, 1.0.1].
    - phpdocumentor/reflection-docblock 4.2.0 requires phpdocumentor/reflection-common ^1.0.0 -> satisfiable by phpdocumentor/reflection-common[1.0, 1.0.1].
    - phpdocumentor/reflection-docblock 4.3.0 requires phpdocumentor/reflection-common ^1.0.0 -> satisfiable by phpdocumentor/reflection-common[1.0, 1.0.1].
    - phpdocumentor/reflection-docblock 4.3.1 requires phpdocumentor/reflection-common ^1.0.0 -> satisfiable by phpdocumentor/reflection-common[1.0, 1.0.1].
    - Can only install one of: phpdocumentor/reflection-common[1.0, 2.2.0].
    - Can only install one of: phpdocumentor/reflection-common[1.0.1, 2.2.0].
    - Installation request for phpdocumentor/reflection-common (locked at 2.2.0) -> satisfiable by phpdocumentor/reflection-common[2.2.0].
    - Installation request for zalas/phpunit-injector ^1.4 -> satisfiable by zalas/phpunit-injector[v1.4.0, v1.4.1, v1.4.2].
    - Conclusion: don't install phpdocumentor/reflection-docblock 5.2.2|install phpdocumentor/reflection-docblock 4.0.1|install phpdocumentor/reflection-docblock 4.1.0|install phpdocumentor/reflection-docblock 4.1.1|install phpdocumentor/reflection-docblock 4.2.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Conclusion: remove phpdocumentor/reflection-docblock 5.2.2|install phpdocumentor/reflection-docblock 4.0.1|install phpdocumentor/reflection-docblock 4.1.0|install phpdocumentor/reflection-docblock 4.1.1|install phpdocumentor/reflection-docblock 4.2.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - zalas/phpunit-injector v1.4.2 requires zalas/injector ^1.3 -> satisfiable by zalas/injector[v1.3.0, v1.3.1].
    - zalas/injector v1.3.1 requires phpdocumentor/reflection-docblock ^4.0.1 -> satisfiable by phpdocumentor/reflection-docblock[4.0.1, 4.1.0, 4.1.1, 4.2.0, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.3.4].
    - zalas/injector v1.3.0 requires phpdocumentor/reflection-docblock ^4.0.1 -> satisfiable by phpdocumentor/reflection-docblock[4.0.1, 4.1.0, 4.1.1, 4.2.0, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.3.4].
    - Can only install one of: phpdocumentor/reflection-docblock[4.3.2, 5.2.2].
    - Can only install one of: phpdocumentor/reflection-docblock[4.3.3, 5.2.2].
    - Can only install one of: phpdocumentor/reflection-docblock[4.3.4, 5.2.2].
    - Installation request for phpdocumentor/reflection-docblock (locked at 5.2.2) -> satisfiable by phpdocumentor/reflection-docblock[5.2.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by jakzal** [comment]
What PHP version are you on?

**Comment by gvojtko** [comment]
PHP7.3, after update to PHP7.4 working well.
